location ~ (^|/)[.] {
  deny all;
  access_log off;
  log_not_found off;
}

location ~* [.]((env)|(log)|(bak)|(backup)|(sql)|(conf)|(ini)|(key)|(pem)|(crt)|(p12)|(sh)|(map))$ {
  deny all;
  access_log off;
  log_not_found off;
}
